    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
require("kalacool.sango.Set.MechanismSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
 level.layers["StaticWorld"].objects["object0"] = WorldSet.newhor_floor({x=300,y=710})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object0"].image)
 level.layers["StaticWorld"].objects["object1"] = WorldSet.newS_hor_floor({x=370,y=660})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object1"].image)
 level.layers["StaticWorld"].objects["object1"].image:rotate(90)
 level.layers["StaticWorld"].objects["object2"] = WorldSet.newM_hor_floor({x=1080,y=710})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object2"].image)
 level.layers["DynamicWorld"].objects["object3"] = WorldSet.newBox({x=1004,y=404})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object3"].image)
 level.layers["DynamicWorld"].objects["object4"] = WorldSet.newCompanionCube({x=1044,y=576})
 level.layers["DynamicWorld"]:insert(level.layers["DynamicWorld"].objects["object4"].image)
 level.layers["Supplement"].objects["object5"] = SupplementSet.newSupShootFaster({x=792,y=652})
 level.layers["Supplement"]:insert(level.layers["Supplement"].objects["object5"].image)
 level.layers["Monster"].objects["object6"] = EnemySet.newMonsterCannon({x=118,y=784})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object6"].image)
 level.layers["StaticWorld"].objects["object7"] = WorldSet.newhor_floor({x=300,y=890})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object7"].image)
 level.layers["Monster"].objects["object8"] = EnemySet.newMonsterSlime({x=376,y=814,xL=100,xR=110})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object8"].image)
 level.layers["StaticWorld"].objects["object9"] = WorldSet.newThorn({x=560,y=820})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object9"].image)
 level.layers["StaticWorld"].objects["object10"] = WorldSet.newCheckDoor({x=610,y=326})
 level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["object10"].image)
 level.layers["InteractiveWorld"].objects["object11"] = WorldSet.newSpinningTire({x=-260,y=-80})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object11"].image)
 level.layers["InteractiveWorld"].objects["object12"] = WorldSet.newSpinningCog({x=160,y=-300})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object12"].image)
 level.layers["InteractiveWorld"].objects["object13"] = WorldSet.newWoodenDoor({x=1246,y=528})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object13"].image)
 level.layers["InteractiveWorld"].objects["object14"] = WorldSet.newDrum({x=1118,y=384})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object14"].image)
 level.layers["InteractiveWorld"].objects["object15"] = WorldSet.newfloatingFloor({x=920,y=850})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object15"].image)
 level.layers["InteractiveWorld"].objects["object16"] = MechanismSet.newDisappearFloor({x=760,y=574})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object16"].image)
 level.layers["InteractiveWorld"].objects["object17"] = WorldSet.newFireBall({x=1326,y=200})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object17"].image)
 level.layers["Monster"].objects["object18"] = EnemySet.newMonsterFireball({x=1190,y=788,xL=100,xR=110})
 level.layers["Monster"]:insert(level.layers["Monster"].objects["object18"].image)
 level.layers["Supplement"].objects["object19"] = SupplementSet.newDogFood({x=866,y=484})
 level.layers["Supplement"]:insert(level.layers["Supplement"].objects["object19"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    return level

end -- CreateLevel