-- Generated by Level Director v2.3.0 on 2013/9/29 ?? 02:18:14

module(..., package.seeall)
require ("sprite")

local storyboard = require( "storyboard" )
local scene = storyboard.newScene()

FloorClass = require ("kalacool.sango.Classes.Objects.World.StaticWorld.Floor")
require ("kalacool.sango.Classes.Objects.World.StaticWorld.Thorn")
require ("kalacool.sango.Classes.Objects.World.DynamicWorld.Box")
require ("kalacool.sango.Classes.Objects.World.DynamicWorld.CompanionCube")
require ("kalacool.sango.Classes.Objects.World.InteractiveWorld.WoodenDoor")
require ("kalacool.sango.Classes.Objects.World.InteractiveWorld.SpinningCog")
require ("kalacool.sango.Classes.Objects.World.InteractiveWorld.FloatingFloor")

imgSubFolder = ""
function CreateLevel(physics)

    display.setDefault( 'background', 105,105,105 )
    physics.setGravity(0,9.8)
    local level = display.newGroup()
    level.layers = {}
    level.name = "Level1-1"

    --- StaticWorld Layer ---

    level.layers["StaticWorld"] = display.newGroup()
    level.layers["StaticWorld"].name = "StaticWorld"

    level.layers["StaticWorld"].objects = {}

	
    level.layers["StaticWorld"].objects["bottomFloor"] = FloorClass.new({x=150,y=800})
    level.layers["StaticWorld"]:insert(level.layers["StaticWorld"].objects["bottomFloor"].image)
    
	
    --- DynamicWorld Layer ---

    level.layers["DynamicWorld"] = display.newGroup()
    level.layers["DynamicWorld"].name = "DynamicWorld"

    level.layers["DynamicWorld"].objects = {}

    

    --- InteractiveWorld Layer ---

    level.layers["InteractiveWorld"] = display.newGroup()
    level.layers["InteractiveWorld"].name = "InteractiveWorld"

    level.layers["InteractiveWorld"].objects = {}


    ------------ End ------------

    level:insert(level.layers["StaticWorld"])
    level:insert(level.layers["DynamicWorld"])
    level:insert(level.layers["InteractiveWorld"])
 	


    return level

end -- CreateLevel