    -- Generated by Kalacool Editor

module(..., package.seeall)
require("kalacool.sango.Set.WorldSet")
require("kalacool.sango.Set.EnemySet")
require("kalacool.sango.Set.SupplementSet")
require("kalacool.sango.Set.MechanismSet")
function CreateLevel(physics)

    display.setDefault( 'background', 0, 0, 0 )
    physics.setGravity(0.0,20.0)
    local collFilter = nil
    local level = display.newGroup()
    level.layers = {}
    level.name = "1-1"

level.layers["StaticWorld"] = display.newGroup()
level.layers["StaticWorld"].name = "StaticWorld"
level.layers["StaticWorld"].objects = {}
level.layers["DynamicWorld"] = display.newGroup()
level.layers["DynamicWorld"].name = "StaticWorld"
level.layers["DynamicWorld"].objects = {}
level.layers["InteractiveWorld"] = display.newGroup()
level.layers["InteractiveWorld"].name = "StaticWorld"
level.layers["InteractiveWorld"].objects = {}
level.layers["Monster"] = display.newGroup()
level.layers["Monster"].name = "Monster"
level.layers["Monster"].objects = {}
level.layers["Supplement"] = display.newGroup()
level.layers["Supplement"].name = "Supplement"
level.layers["Supplement"].objects = {}
level.layers["Image"] = display.newGroup()
level.layers["Image"].name = "Image"
level.layers["Image"].objects = {}
 level.layers["InteractiveWorld"].objects["object0"] = MechanismSet.newDestructibleBlockSand({x=950,y=690})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object0"].image)
 level.layers["InteractiveWorld"].objects["object1"] = MechanismSet.newDestructibleBlockSand({x=1010,y=690})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object1"].image)
 level.layers["InteractiveWorld"].objects["object2"] = MechanismSet.newDestructibleBlockSand({x=1070,y=690})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object2"].image)
 level.layers["InteractiveWorld"].objects["object3"] = MechanismSet.newDestructibleBlockSand({x=1130,y=690})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object3"].image)
 level.layers["InteractiveWorld"].objects["object4"] = MechanismSet.newDestructibleBlockSand({x=1190,y=690})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object4"].image)
 level.layers["InteractiveWorld"].objects["object5"] = MechanismSet.newDestructibleBlockSand({x=1250,y=690})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object5"].image)
 level.layers["InteractiveWorld"].objects["object6"] = MechanismSet.newDestructibleBlockObs({x=950,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object6"].image)
 level.layers["InteractiveWorld"].objects["object7"] = MechanismSet.newDestructibleBlockObs({x=1010,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object7"].image)
 level.layers["InteractiveWorld"].objects["object8"] = MechanismSet.newDestructibleBlockObs({x=1070,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object8"].image)
 level.layers["InteractiveWorld"].objects["object9"] = MechanismSet.newDestructibleBlockObs({x=1130,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object9"].image)
 level.layers["InteractiveWorld"].objects["object10"] = MechanismSet.newDestructibleBlockObs({x=1190,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object10"].image)
 level.layers["InteractiveWorld"].objects["object11"] = MechanismSet.newDestructibleBlockObs({x=1250,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object11"].image)
 level.layers["InteractiveWorld"].objects["object12"] = MechanismSet.newDestructibleBlockObs({x=1310,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object12"].image)
 level.layers["InteractiveWorld"].objects["object13"] = MechanismSet.newDestructibleBlockObs({x=1370,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object13"].image)
 level.layers["InteractiveWorld"].objects["object14"] = MechanismSet.newDestructibleBlockObs({x=1430,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object14"].image)
 level.layers["InteractiveWorld"].objects["object15"] = MechanismSet.newDestructibleBlockObs({x=1490,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object15"].image)
 level.layers["InteractiveWorld"].objects["object16"] = MechanismSet.newDestructibleBlockObs({x=1550,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object16"].image)
 level.layers["InteractiveWorld"].objects["object17"] = MechanismSet.newDestructibleBlockObs({x=1610,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object17"].image)
 level.layers["InteractiveWorld"].objects["object18"] = MechanismSet.newDestructibleBlockObs({x=1670,y=750})
 level.layers["InteractiveWorld"]:insert(level.layers["InteractiveWorld"].objects["object18"].image)
    level:insert(level.layers["StaticWorld"])

    level:insert(level.layers["DynamicWorld"])

    level:insert(level.layers["InteractiveWorld"])

    level:insert(level.layers["Monster"])

    level:insert(level.layers["Supplement"])

    level:insert(level.layers["Image"])

    return level

end -- CreateLevel